name: npm audit
author: Mike Hockerman (@mhoc)
description: runs an analysis of your nodejs dependencies and comments the results back to the pr
runs:
  using: node12
  main: dist/index.js
inputs:
  comment-pr:
    description: provide 'true' or 'false' to control whether the action should comment the results back to the pull request.
    required: false
    default: "true"
  elide-attribtion:
    description: by default, this generates a final line that links back to this repository, to provide a hyperlink for submitting bugs and such. set to 'true' to remove this.
    required: false
    default: "false"
  fail-on-outdated:
    description: provide 'true' to fail the workflow if any outdated packages are found
    required: false
    default: "false"
  fail-on-vulnerability:
    description: provide 'true' to fail the workflow if any vulnerabilities are found
    required: false
    default: "false"
outputs:
  total-dependencies:
    description: the total number of transitive dependencies your project has
  total-vulnerabilities:
    description: the total number of open vulnerabilities your project has
